// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3UZwCq_qUBb4wBDuBRAWY7WKi_tTUdRM',
    appId: '1:157938247391:web:3c62cd51870a467f6bab6a',
    messagingSenderId: '157938247391',
    projectId: 'fieldfilm-374df',
    authDomain: 'fieldfilm-374df.firebaseapp.com',
    storageBucket: 'fieldfilm-374df.firebasestorage.app',
    measurementId: 'G-ESTM9Z012J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGZQbvWUEf7_80V4tC6fd1U-SmapP_D-s',
    appId: '1:157938247391:android:5c9ddaabd240958a6bab6a',
    messagingSenderId: '157938247391',
    projectId: 'fieldfilm-374df',
    storageBucket: 'fieldfilm-374df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiiFK4Vsb4pH8Ul9G58m8cZNES1RelIEw',
    appId: '1:157938247391:ios:6ccb635502d58d356bab6a',
    messagingSenderId: '157938247391',
    projectId: 'fieldfilm-374df',
    storageBucket: 'fieldfilm-374df.firebasestorage.app',
    iosBundleId: 'com.example.fieldfilm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiiFK4Vsb4pH8Ul9G58m8cZNES1RelIEw',
    appId: '1:157938247391:ios:6ccb635502d58d356bab6a',
    messagingSenderId: '157938247391',
    projectId: 'fieldfilm-374df',
    storageBucket: 'fieldfilm-374df.firebasestorage.app',
    iosBundleId: 'com.example.fieldfilm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3UZwCq_qUBb4wBDuBRAWY7WKi_tTUdRM',
    appId: '1:157938247391:web:aae6cbcdf2ee40516bab6a',
    messagingSenderId: '157938247391',
    projectId: 'fieldfilm-374df',
    authDomain: 'fieldfilm-374df.firebaseapp.com',
    storageBucket: 'fieldfilm-374df.firebasestorage.app',
    measurementId: 'G-E9XGBV0RX9',
  );
}
